spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      uri: mongodb://docomo:Docomo01@mongodb/testdb
      database: testdb
      username: docomo
      password: Docomo01
      repositories:
        type: auto